server:
  port:
    8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/GoogleOauth
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  application:
    name:
      demo
  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            clientId: 1062665072865-8dhbc8sil84rgpmsmoleou1v86244qt0.apps.googleusercontent.com
#            clientSecret: "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"
#            scope: openid, profile, email
google:
            clientId: 1062665072865-8dhbc8sil84rgpmsmoleou1v86244qt0.apps.googleusercontent.com
            clientSecret: "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"
            redirectURI: "http://localhost/8090/oauth2/callback/{registrationId}"
            scope: openid, profile, email

logging:
  level:
    org.springframework.security: DEBUG


debug: true
