server:
  port:
    8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/GoogleOauth
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  application:
    name:
      demo
google:
  clientId: 1062665072865-8dhbc8sil84rgpmsmoleou1v86244qt0.apps.googleusercontent.com

logging:
  level:
    org.springframework.security: DEBUG


debug: true
