server:
  port:
    8090
spring:
  application:
    name:
      demo
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
      client:
        registration:
          google:
            client-id: 1062665072865-8dhbc8sil84rgpmsmoleou1v86244qt0.apps.googleusercontent.com
            client-secret: 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
            scope: openid,email
            redirect-uri: http://localhost:8090/login/oauth2/code/google
logging:
  level:
    org.springframework.security: DEBUG


debug: true
